### ISSUE TITLE
add support for encryption

### ISSUE THREAD

**Issue by FyrN22** [FakeShell/droidian-oneplus6#1]

**Comment by FakeShell** [comment]
the reason encryption does not work (or rather it does encrypt but cannot unlock) is because of touchscreen firmware not loading at all in the ramdisk. to fix it, porters have to look at the boot process from the moment the container starts. and check which firmware is loaded for the touchscreen to which node (maybe fts_force_upgrade, maybe something else). then it can be added as a hook to the ramdisk like so:
https://github.com/droidian-devices/linux-android-fxtec-pro1x/blob/droidian/debian/initramfs-overlay/scripts/halium-hooks

**Comment by d4nj1** [comment]
I guess this is fixed, see https://mastodon.ml/@Evv1L/111708049978938037
Tried it and works like a charm.

**Comment by FakeShell** [comment]
Fixed by: https://github.com/droidian/lxc-android/commit/b3c89b25ebaa68037d9784e9bff26920826c91ed

Closing
