### ISSUE TITLE
4G support 

### ISSUE THREAD

**Issue by as400l** [FakeShell/droidian-oneplus6#4]
Hey,

So I installed Droidian on my OP6. I have APN for data defined. But, where I live, phone for calls uses 3G. And it displays 3G next to mobile network icon even though for data it is using 4G because I can see it judging by performance. Now, maybe it is not an issue and that's how it should be but on PmOS it's the other way around - it displays 4G even though for calls it is using 3G.

BTW - this port is just working great !!! All the features are there. Thanks for your work !!! Why isn't this port official ?

**Comment by as400l** [comment]
That was kind of lame of me.
So the modem supports only certain combinations of "allowed modes" and if you try to select the one that modem doesn't support then selection will fail (in my case I tried 3G,4G(preferred).
So to resolve this "issue" it's enough to choose "2G,3G,4G(preferred)" and all is fine. It displays 4G next to signal level.

**Comment by FakeShell** [comment]
Allowed modes are limited to what ofono itself supports. Currently being gprs umts lte nr
Ofono2mm reads the highest mode available and sets it as available for apps requiring modem manager
I don't have any issues myself as calls drop down to 2g and go back to 4g automatically. Maybe a bit more info on how this happens and what the expected behavior should be could help.
Only devices that one of us core developers own can be added to official because of how our ci system works and the track record of the community leaving half assed ports.

**Comment by as400l** [comment]
I think I maybe didn't make myself clear enough. Not an issue actually. All is fine. Closing it.

As to the official releases. Looks like OP6 is the best supported phone in terms of working features. I mean all official ones have more non working features than OP6 :)

**Comment by FakeShell** [comment]
i would have to disagree. in terms of quality it is not even close to galaxy s9 or pixel 3a or any of the miatoll devices. fxtec and sony all have everything working but their device page is outdated.
